name: dartmon
description: A simple command-line application.
version: 1.0.0
homepage: https://github.com/Akash98Sky/dartmon.git

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  ansicolor: ^1.1.1
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.9.0
